import type { MetricDef, MetricId, ModuleDef, ModuleId } from "@/types/metrics";

export const MODULES: ModuleDef[] = [
  {
    id: "markets",
    title: "Markets",
    description: "Spot price and monetary framing",
    source: "mempool.space",
    metricIds: ["price_usd", "sats_per_dollar", "market_cap"],
  },
  {
    id: "blockchain",
    title: "Blockchain",
    description: "Chain tip and confirmation cadence",
    source: "mempool.space",
    metricIds: ["block_height", "time_since_block", "tip_hash"],
  },
  {
    id: "mempool",
    title: "Mempool",
    description: "Unconfirmed demand waiting for the next block",
    source: "mempool.space",
    metricIds: ["mempool_count", "mempool_vsize", "mempool_pressure"],
  },
  {
    id: "fees",
    title: "Fee Estimates",
    description: "Suggested sat/vB for target confirmation windows",
    source: "mempool.space",
    metricIds: ["fee_fastest", "fee_half_hour", "fee_hour", "fee_economy"],
  },
  {
    id: "mining",
    title: "Mining",
    description: "Hashpower and difficulty retarget",
    source: "mempool.space",
    metricIds: [
      "hashrate",
      "difficulty",
      "retarget_progress",
      "retarget_change",
      "retarget_blocks",
    ],
  },
  {
    id: "halving",
    title: "Halving",
    description: "Subsidy schedule toward the next epoch",
    source: "derived",
    metricIds: [
      "halving_epoch",
      "halving_blocks",
      "halving_date",
      "halving_progress",
    ],
  },
  {
    id: "lightning",
    title: "Lightning Network",
    description: "Public channel graph snapshot",
    source: "mempool.space",
    metricIds: ["ln_capacity", "ln_nodes", "ln_channels"],
  },
  {
    id: "supply",
    title: "Supply",
    description: "Issued coins versus the 21M hard cap",
    source: "derived",
    metricIds: ["money_supply", "pct_issued"],
  },
];

export const METRICS: MetricDef[] = [
  {
    id: "price_usd",
    module: "markets",
    label: "Price",
    definition: "Bitcoin spot price in US dollars from mempool.space aggregated feeds.",
    source: "mempool.space",
    format: "usd",
    higherIsBetter: true,
    pinDefault: true,
  },
  {
    id: "sats_per_dollar",
    module: "markets",
    label: "Sats per Dollar",
    definition: "How many satoshis one US dollar buys at the current spot price.",
    source: "derived",
    format: "sats",
    higherIsBetter: false,
    pinDefault: true,
  },
  {
    id: "market_cap",
    module: "markets",
    label: "Market Cap",
    definition: "Spot price multiplied by issued circulating supply.",
    source: "derived",
    format: "usd",
    higherIsBetter: true,
  },
  {
    id: "block_height",
    module: "blockchain",
    label: "Block Height",
    definition: "Number of blocks in the best chain from genesis to tip.",
    source: "mempool.space",
    format: "integer",
    higherIsBetter: true,
    pinDefault: true,
  },
  {
    id: "time_since_block",
    module: "blockchain",
    label: "Time Since Last Block",
    definition: "Elapsed time since the tip block was found. Network targets ~10 minutes.",
    source: "mempool.space",
    format: "duration",
    higherIsBetter: false,
    pinDefault: true,
  },
  {
    id: "tip_hash",
    module: "blockchain",
    label: "Tip Hash",
    definition: "Block hash of the current chain tip.",
    source: "mempool.space",
    format: "hash",
  },
  {
    id: "mempool_count",
    module: "mempool",
    label: "Pending Transactions",
    definition: "Count of unconfirmed transactions currently in the observed mempool.",
    source: "mempool.space",
    format: "integer",
    higherIsBetter: false,
    pinDefault: true,
  },
  {
    id: "mempool_vsize",
    module: "mempool",
    label: "Mempool Size",
    definition: "Virtual size of all pending transactions waiting for confirmation.",
    source: "mempool.space",
    format: "vsize",
    higherIsBetter: false,
  },
  {
    id: "mempool_pressure",
    module: "mempool",
    label: "Mempool Pressure",
    definition:
      "Rough fullness versus a 1-block (~1.0 MB vsize) baseline. Above 100% means backlog.",
    source: "derived",
    format: "percent",
    higherIsBetter: false,
  },
  {
    id: "fee_fastest",
    module: "fees",
    label: "Immediate",
    definition: "Fee rate recommended for next-block inclusion when possible.",
    source: "mempool.space",
    format: "fee",
    higherIsBetter: false,
    pinDefault: true,
  },
  {
    id: "fee_half_hour",
    module: "fees",
    label: "Half Hour",
    definition: "Fee rate estimated for confirmation within about 30 minutes.",
    source: "mempool.space",
    format: "fee",
    higherIsBetter: false,
  },
  {
    id: "fee_hour",
    module: "fees",
    label: "One Hour",
    definition: "Fee rate estimated for confirmation within about an hour.",
    source: "mempool.space",
    format: "fee",
    higherIsBetter: false,
  },
  {
    id: "fee_economy",
    module: "fees",
    label: "Economy",
    definition: "Low-priority fee suitable when confirmation can wait.",
    source: "mempool.space",
    format: "fee",
    higherIsBetter: false,
  },
  {
    id: "hashrate",
    module: "mining",
    label: "Hashrate",
    definition: "Estimated network hashrate over the recent mining window.",
    source: "mempool.space",
    format: "hashrate",
    higherIsBetter: true,
    pinDefault: true,
  },
  {
    id: "difficulty",
    module: "mining",
    label: "Difficulty",
    definition: "Current proof-of-work difficulty target.",
    source: "mempool.space",
    format: "eh",
    higherIsBetter: true,
  },
  {
    id: "retarget_progress",
    module: "mining",
    label: "Retarget Progress",
    definition: "Progress through the current 2016-block difficulty epoch.",
    source: "mempool.space",
    format: "percent",
    higherIsBetter: true,
  },
  {
    id: "retarget_change",
    module: "mining",
    label: "Est. Difficulty Change",
    definition: "Predicted difficulty adjustment at the next retarget.",
    source: "mempool.space",
    format: "percent",
    higherIsBetter: true,
  },
  {
    id: "retarget_blocks",
    module: "mining",
    label: "Blocks to Retarget",
    definition: "Blocks remaining until the next difficulty adjustment.",
    source: "mempool.space",
    format: "integer",
    higherIsBetter: false,
  },
  {
    id: "halving_epoch",
    module: "halving",
    label: "Subsidy Epoch",
    definition: "Current subsidy epoch. Epoch 1 began at genesis; each halving starts a new epoch.",
    source: "derived",
    format: "integer",
    higherIsBetter: true,
  },
  {
    id: "halving_blocks",
    module: "halving",
    label: "Blocks to Halving",
    definition: "Blocks remaining until the block subsidy halves again.",
    source: "derived",
    format: "integer",
    higherIsBetter: false,
    pinDefault: true,
  },
  {
    id: "halving_date",
    module: "halving",
    label: "Halving Estimate",
    definition: "Estimated date of the next halving assuming ~10 minute blocks.",
    source: "derived",
    format: "date",
  },
  {
    id: "halving_progress",
    module: "halving",
    label: "Epoch Progress",
    definition: "Percent of the current 210,000-block subsidy epoch completed.",
    source: "derived",
    format: "percent",
    higherIsBetter: true,
  },
  {
    id: "ln_capacity",
    module: "lightning",
    label: "Public Capacity",
    definition: "Bitcoin locked in publicly announced Lightning channels.",
    source: "mempool.space",
    format: "btc",
    higherIsBetter: true,
    pinDefault: true,
  },
  {
    id: "ln_nodes",
    module: "lightning",
    label: "Public Nodes",
    definition: "Count of publicly visible Lightning nodes.",
    source: "mempool.space",
    format: "integer",
    higherIsBetter: true,
  },
  {
    id: "ln_channels",
    module: "lightning",
    label: "Public Channels",
    definition: "Count of publicly announced Lightning channels.",
    source: "mempool.space",
    format: "integer",
    higherIsBetter: true,
  },
  {
    id: "money_supply",
    module: "supply",
    label: "Money Supply",
    definition: "Total BTC issued via block subsidies through the current tip.",
    source: "derived",
    format: "btc",
    higherIsBetter: true,
  },
  {
    id: "pct_issued",
    module: "supply",
    label: "Percentage Issued",
    definition: "Issued supply as a percentage of the 21 million hard cap.",
    source: "derived",
    format: "percent",
    higherIsBetter: true,
  },
];

export const METRIC_BY_ID: Record<MetricId, MetricDef> = Object.fromEntries(
  METRICS.map((m) => [m.id, m]),
) as Record<MetricId, MetricDef>;

export const MODULE_BY_ID: Record<ModuleId, ModuleDef> = Object.fromEntries(
  MODULES.map((m) => [m.id, m]),
) as Record<ModuleId, ModuleDef>;

export const DEFAULT_FAVORITES: MetricId[] = METRICS.filter((m) => m.pinDefault).map(
  (m) => m.id,
);

export function metricsForModule(moduleId: ModuleId): MetricDef[] {
  return METRICS.filter((m) => m.module === moduleId);
}
